version: 2.1

orbs:
  unumid: unumid/unumid-app-orb@2.0.0

workflows:
  lint-and-test:
    jobs:
      - unumid/lint-and-test:
          compile_script_name: build
          filters:
            branches:
              ignore:
                - main

  build-and-deploy:
    jobs:
      - unumid/lint-and-test:
          compile_script_name: build
          enable_slack_failure_notification: true
          filters:
            branches:
              only:
                - main

      - unumid/build-and-push-image:
          requires:
            - unumid/lint-and-test
          context:
            - AWS-Root-Account
            - Slack-Context
          account_id_1: '408067220840'
          repo: hooli-demo-web # update with actual repo name
          image_tag_1: '${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}'
          image_tag_2: dev-latest
          filters:
            branches:
              only:
                - main

      - unumid/build-and-upload-sentry-sourcemaps:
          requires:
            - unumid/lint-and-test
          context:
            - Slack-Context
            - Sentry-Context
          script_name: sentry:upload_sourcemaps
          compile_script_name: build:sourcemap
          cache_version: v6
          sentry_org: verified-network
          sentry_project: hooli-demo-web
          filters:
            branches:
              only:
                - main

      - unumid/deploy-image:
          name: unumid/deploy-image-dev
          requires:
            - unumid/build-and-push-image
          context:
            - AWS-Root-Account
            - Slack-Context
          account_id: '408067220840'
          repo: hooli-demo-web # update with actual repo name
          deployment: hooli-demo-web # update with actual deployment name
          cluster_name: dev-account-saas-cluster
          namespace: demos
          image_tag: dev-latest
          filters:
            branches:
              only:
                - main

      # - unumid/deploy-image:
      #     name: unumid/deploy-image-dev-partner
      #     requires:
      #       - unumid/build-and-push-image
      #     context:
      #       - AWS-Root-Account
      #       - Slack-Context
      #     account_id: '408067220840'
      #     repo: hooli-demo-web # update with actual repo name
      #     deployment: hooli-partner-demo-web # update with actual deployment name
      #     cluster_name: dev-account-saas-cluster
      #     namespace: demos
      #     image_tag: dev-latest
      #     filters:
      #       branches:
      #         only:
      #           - main

  build-and-deploy-staging:
    jobs:
      - unumid/lint-and-test:
          compile_script_name: build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
            branches:
              ignore: /.*/

      - unumid/build-and-push-image:
          name: unumid/build-and-push-image-staging
          requires:
            - unumid/lint-and-test
          context:
            - AWS-Root-Account
            - Slack-Context
          account_id_1: 058264190665
          account_id_3: 032538391126 # purposely using the sandbox account for 3, because the ecr repo does not exist in
          publish_image_tag_1: true
          repo: hooli-demo-web # update with actual repo name
          image_tag_1: '${CIRCLE_TAG}'
          image_tag_2: staging-latest
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
            branches:
              ignore: /.*/

      - unumid/build-and-upload-sentry-sourcemaps:
          requires:
            - unumid/lint-and-test
          context:
            - Slack-Context
            - Sentry-Context
          script_name: sentry:upload_sourcemaps
          compile_script_name: build:sourcemap
          cache_version: v6
          sentry_org: verified-network
          sentry_project: hooli-demo-web
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
            branches:
              ignore: /.*/

      - unumid/deploy-image:
          name: unumid/deploy-image-staging
          requires:
            - unumid/build-and-push-image-staging
          context:
            - AWS-Root-Account
            - Slack-Context
          account_id: 058264190665
          repo: hooli-demo-web # update with actual repo name
          deployment: hooli-demo-web # update with actual deployment name
          cluster_name: staging-account-core-cluster
          namespace: demos
          image_tag: '${CIRCLE_TAG}'
          slack_pass_notify_template: success_tagged_deploy_1
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
            branches:
              ignore: /.*/

      # - unumid/deploy-image:
      #     name: unumid/deploy-image-staging-partner
      #     requires:
      #       - unumid/build-and-push-image-staging
      #     context:
      #       - AWS-Root-Account
      #       - Slack-Context
      #     account_id: 058264190665
      #     repo: hooli-demo-web # update with actual repo name
      #     deployment: hooli-partner-demo-web # update with actual deployment name
      #     cluster_name: staging-account-core-cluster
      #     namespace: demos
      #     image_tag: '${CIRCLE_TAG}'
      #     slack_pass_notify_template: success_tagged_deploy_1
      #     filters:
      #       tags:
      #         only: /^v\d+\.\d+\.\d+/
      #       branches:
      #         ignore: /.*/

  build-and-deploy-test:
    jobs:
      - unumid/build-and-push-image:
          name: unumid/build-and-push-image-test
          context:
            - AWS-Root-Account
            - Slack-Context
          account_id_1: '408067220840'
          repo: hooli-demo-web # update with actual repo name
          image_tag_1: '${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}'
          image_tag_2: test-latest
          filters:
            branches:
              only:
                - test-circleci

      - unumid/build-and-upload-sentry-sourcemaps:
          context:
            - Slack-Context
            - Sentry-Context
          script_name: sentry:upload_sourcemaps
          compile_script_name: build:sourcemap
          cache_version: v6
          sentry_org: verified-network
          sentry_project: hooli-demo-web
          filters:
            branches:
              only:
                - test-circleci

      - unumid/deploy-image:
          name: unumid/deploy-image-test
          requires:
            - unumid/build-and-push-image-test
          context:
            - AWS-Root-Account
            - Slack-Context
          account_id: '408067220840'
          repo: hooli-demo-web # update with actual repo name
          deployment: hooli-demo-web # update with actual deployment name
          cluster_name: dev-account-saas-cluster
          namespace: demos
          image_tag: test-latest
          filters:
            branches:
              only:
                - test-circleci
      # - unumid/deploy-image:
      #     name: unumid/deploy-image-test-partner
      #     requires:
      #       - unumid/build-and-push-image-test
      #     context:
      #       - AWS-Root-Account
      #       - Slack-Context
      #     account_id: '408067220840'
      #     repo: hooli-demo-web # update with actual repo name
      #     deployment: hooli-partner-demo-web # update with actual deployment name
      #     cluster_name: dev-account-saas-cluster
      #     namespace: demos
      #     image_tag: test-latest
      #     filters:
      #       branches:
      #         only:
      #           - test-circleci
